spring:
  application:
    name: edge-service

  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service-public
            uri: http://localhost:8082
            predicates:
              - Path=/public/api/v1/users/**

          - id: user-service-secure
            uri: http://localhost:8082
            predicates:
              - Path=/secure/api/v1/users/**

          - id: movie-service-public
            uri: http://localhost:8081
            predicates:
              - Path=/public/api/v1/movies/**

          - id: movie-service-secure
            uri: http://localhost:8081
            predicates:
              - Path=/secure/api/v1/movies/**

server:
  port: 8080

kakao:
  client:
    id: 3c46ac9fcd53813acad0147afe8d5a31

jwt:
  secretKey: polarMoviechartJwtSecretPolarMoviechartJwtSecret
